### ISSUE TITLE
Workshop Spawner does not launch on OCP 4.7.13

### ISSUE THREAD

**Issue by bkoz** [RedHatGov/serverless-workshop-code#18]
The serverless-workshop-spawner pod runs but the [logs](http://pastebin.test.redhat.com/974298) indicate problems. 

```
$ oc version
Client Version: 4.7.13
Server Version: 4.7.13
Kubernetes Version: v1.20.0+df9c838
```

**Comment by theckang** [comment]
The workshop is provisioned using RHPDS which pins on 4.8.  I suspect there may have been issues if the spawner was run on a custom BYO cluster.  With the RHPDS catalog item, the spawner has no errors and we will recommend workshop coordinators to provision using RHPDS to avoid any errors.
